"use client"
import { Link } from "react-router-dom"
import { useAuth } from "../contexts/AuthContext"
import { FiArrowRight, FiZap, FiTarget, FiTrendingUp, FiUsers } from "react-icons/fi"

const Landing = () => {
  const { user } = useAuth()

  const features = [
    {
      icon: FiZap,
      title: "AI-Powered Questions",
      description:
        "Get personalized interview questions generated by advanced AI based on your chosen domain and difficulty level.",
    },
    {
      icon: FiTarget,
      title: "Instant Feedback",
      description:
        "Receive detailed AI feedback on your answers with specific suggestions for improvement and scoring.",
    },
    {
      icon: FiTrendingUp,
      title: "Progress Tracking",
      description: "Monitor your improvement over time with detailed analytics and performance insights.",
    },
    {
      icon: FiUsers,
      title: "Competitive Learning",
      description: "Compare your performance with other users on the leaderboard and stay motivated.",
    },
  ]

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="bg-gradient-to-br from-primary-50 to-primary-100 py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
              Master Your Next
              <span className="text-primary-600 block">Interview</span>
            </h1>
            <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
              Prepare for technical interviews with AI-generated questions, instant feedback, and personalized learning
              paths. Practice across multiple domains and difficulty levels.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              {user ? (
                <Link to="/dashboard" className="btn-primary text-lg px-8 py-3 inline-flex items-center">
                  Go to Dashboard
                  <FiArrowRight className="ml-2 w-5 h-5" />
                </Link>
              ) : (
                <>
                  <Link to="/signup" className="btn-primary text-lg px-8 py-3 inline-flex items-center">
                    Start Practicing
                    <FiArrowRight className="ml-2 w-5 h-5" />
                  </Link>
                  <Link to="/login" className="btn-secondary text-lg px-8 py-3">
                    Login
                  </Link>
                </>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Why Choose AI Interview Prep?</h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our platform combines cutting-edge AI technology with proven interview preparation methods
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="card text-center hover:shadow-md transition-shadow">
                <div className="w-12 h-12 bg-primary-100 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <feature.icon className="w-6 h-6 text-primary-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">{feature.title}</h3>
                <p className="text-gray-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-primary-600">
        <div className="max-w-4xl mx-auto text-center px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">Ready to Ace Your Interview?</h2>
          <p className="text-xl text-primary-100 mb-8">
            Join thousands of developers who have improved their interview skills with our AI-powered platform
          </p>
          {!user && (
            <Link
              to="/signup"
              className="bg-white text-primary-600 hover:bg-gray-100 font-semibold py-3 px-8 rounded-lg transition-colors inline-flex items-center"
            >
              Get Started Free
              <FiArrowRight className="ml-2 w-5 h-5" />
            </Link>
          )}
        </div>
      </section>
    </div>
  )
}

export default Landing
